=== evan-vivasoft/InspectorPC/38000405_Inspector_PC/SIOUX Source/Inspector.UI.Initialization/SIOUX Source/Inspector.BusinessLogic.Data.Reporting.Test/XSD/ObjectInformation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Michel de Clercq (Kamstrup R&D) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="Objects">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ObjectInformation" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ObjectName" type="xsd:string"/>
							<xsd:element name="MeasurePoint" type="xsd:string"/>
							<xsd:element name="FieldNo" type="xsd:string" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== evan-vivasoft/InspectorPC/38000405_Inspector_PC/SIOUX Source/Inspector.UI.Initialization/SIOUX Source/Inspector.BusinessLogic.Data.Reporting.Test/XML/ObjectInformation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 (http://www.altova.com)-->
<Objects xsi:noNamespaceSchemaLocation="H:\mijn%20documenten\CONNEXION\Systeembeschrijving\Indeling%20XML%20berichten\ObjectInformation.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ObjectInformation>
		<ObjectName>String</ObjectName>
		<MeasurePoint>String</MeasurePoint>
		<FieldNo>String</FieldNo>
	</ObjectInformation>
	<ObjectInformation>
		<ObjectName>String</ObjectName>
		<MeasurePoint>String</MeasurePoint>
		<FieldNo>String</FieldNo>
	</ObjectInformation>
	<ObjectInformation>
		<ObjectName>String</ObjectName>
		<MeasurePoint>String</MeasurePoint>
		<FieldNo>String</FieldNo>
	</ObjectInformation>
	<ObjectInformation>
		<ObjectName>String</ObjectName>
		<MeasurePoint>String</MeasurePoint>
		<FieldNo>String</FieldNo>
	</ObjectInformation>
</Objects>
