=== evan-vivasoft/InspectorPC/SIOUX Source/Inspector.UI.Initialization/SIOUX Source/Inspector.BusinessLogic.Data.Configuration/InspectionManager/Data/InspectionProcedure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 sp1 (http://www.altova.com) by Michel De Clercq (Kamstrup b.v.) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="InspectionProcedureFile">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="InspectionProcedure" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Name" type="xsd:string"/>
							<xsd:element name="Version" type="xsd:string"/>
							<xsd:element name="InspectionSequence">
								<xsd:annotation>
									<xsd:documentation>A measure point contains several ID's. The ObjectID and MeasurePoint are linked to the ObjectID and MeasurepointID in the station data or gas control line data. In the inspection result these ID's and the MeasurePointID are saved. It is only possible to select only Scriptcommand_4 or Scriptcommand_41 or Scriptcommand_42 or Scriptcommand_43 or one Scriptcommand_51 </xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:choice maxOccurs="unbounded">
											<xsd:element name="Scriptcommand_1" minOccurs="0" maxOccurs="unbounded">
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="Text" type="xsd:string"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_2" minOccurs="0" maxOccurs="unbounded">
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="Section" type="xsd:string"/>
														<xsd:element name="SubSection" type="xsd:string"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_3" minOccurs="0" maxOccurs="unbounded">
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="Text" type="xsd:string"/>
														<xsd:element name="Duration" type="xsd:positiveInteger"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_70" minOccurs="0" maxOccurs="unbounded">
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="Mode" type="xsd:boolean"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_4" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>Question to the inspector. The selected or inputted data is saved in the inspection result</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="ObjectName" type="xsd:string" minOccurs="0"/>
														<xsd:element name="MeasurePoint" type="xsd:string" minOccurs="0"/>
														<xsd:element name="FieldNo" type="xsd:integer" minOccurs="0"/>
														<xsd:element name="Question" type="xsd:string"/>
														<xsd:element name="TypeQuestion">
															<xsd:simpleType>
																<xsd:restriction base="xsd:string">
																	<xsd:enumeration value="0; Input multi lines"/>
																	<xsd:enumeration value="1; Input single line"/>
																	<xsd:enumeration value="2; 2 options"/>
																	<xsd:enumeration value="3; 3 options"/>
																</xsd:restriction>
															</xsd:simpleType>
														</xsd:element>
														<xsd:element name="TextOptions" type="xsd:string" minOccurs="0" maxOccurs="3"/>
														<xsd:element name="Required" type="xsd:boolean"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_41" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>Option (one or more selections per list) and check lists. Displaying maximum 5 lists with 12 options per list</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="ObjectName" type="xsd:string" minOccurs="0"/>
														<xsd:element name="MeasurePoint" type="xsd:string" minOccurs="0"/>
														<xsd:element name="FieldNo" type="xsd:integer" minOccurs="0"/>
														<xsd:element name="ShowNextListImmediately" type="xsd:boolean">
															<xsd:annotation>
																<xsd:documentation>In case of a checklist; when selecting a condition code the next list will be displayed immediatialy</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="List" maxOccurs="5">
															<xsd:complexType>
																<xsd:sequence>
																	<xsd:element name="SequenceNumberList" type="xsd:long"/>
																	<xsd:element name="ListType">
																		<xsd:simpleType>
																			<xsd:restriction base="xsd:string">
																				<xsd:enumeration value="0;OptionList"/>
																				<xsd:enumeration value="1;CheckList"/>
																			</xsd:restriction>
																		</xsd:simpleType>
																	</xsd:element>
																	<xsd:element name="SelectionRequired" type="xsd:boolean" minOccurs="0"/>
																	<xsd:element name="ListQuestion" type="xsd:string"/>
																	<xsd:element name="OneSelectionAllowed" type="xsd:boolean">
																		<xsd:annotation>
																			<xsd:documentation>Only one condition code can be selected in a list</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="CheckListResult" type="xsd:boolean">
																		<xsd:annotation>
																			<xsd:documentation>False; In case of a checklist; the value ;0 (Not Ok) or ;1 (OK) will not be stored in the inspection results( </xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="ListConditionCode" maxOccurs="12">
																		<xsd:complexType>
																			<xsd:sequence>
																				<xsd:element name="ConditionCode" type="xsd:string"/>
																				<xsd:element name="ConditionCodeDescription" type="xsd:string"/>
																				<xsd:element name="DisplayNextList" type="xsd:boolean"/>
																			</xsd:sequence>
																		</xsd:complexType>
																	</xsd:element>
																</xsd:sequence>
															</xsd:complexType>
														</xsd:element>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_42" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>Saving input of the inspector in the remark window of INSPECTOR in the inspection results</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="ObjectName" type="xsd:string" minOccurs="0"/>
														<xsd:element name="MeasurePoint" type="xsd:string" minOccurs="0"/>
														<xsd:element name="FieldNo" type="xsd:integer" minOccurs="0"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_43" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>List of maximum 20 choices from which the inspector can select. Selection required</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="SequenceNumber" type="xsd:long"/>
														<xsd:element name="ObjectName" type="xsd:string" minOccurs="0"/>
														<xsd:element name="MeasurePoint" type="xsd:string" minOccurs="0"/>
														<xsd:element name="FieldNo" type="xsd:integer" minOccurs="0"/>
														<xsd:element name="Instruction" type="xsd:string"/>
														<xsd:element name="ListItem" type="xsd:string" minOccurs="2" maxOccurs="20"/>
														<xsd:element name="Required" type="xsd:boolean"/>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Scriptcommand_5x" type="TypeScriptcommand5x" minOccurs="0" maxOccurs="unbounded"/>
										</xsd:choice>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="TypeScriptcommand5x">
		<xsd:annotation>
			<xsd:documentation>The different scriptcommands 5x. Reading the pressure from the digital manometer.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SequenceNumber" type="xsd:long"/>
			<xsd:element name="ObjectName" type="xsd:string" minOccurs="0"/>
			<xsd:element name="MeasurePoint" type="xsd:string" minOccurs="0"/>
			<xsd:element name="FieldNo" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="Scriptcommand">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="51"/>
						<xsd:enumeration value="52"/>
						<xsd:enumeration value="53"/>
						<xsd:enumeration value="54"/>
						<xsd:enumeration value="55"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Instruction" type="xsd:string" minOccurs="0"/>
			<xsd:element name="DigitalManometer" type="TypeDigitalManometer"/>
			<xsd:element name="MeasurementFrequency" type="TypeMeasurementFrequency"/>
			<xsd:element name="MeasurementPeriod" type="xsd:nonNegativeInteger"/>
			<xsd:element name="ExtraMeasurementPeriod" type="xsd:nonNegativeInteger"/>
			<xsd:element name="Leakage" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Select the type of leakage. More information in the manual of CONNEXION </xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="V1"/>
						<xsd:enumeration value="V2"/>
						<xsd:enumeration value="Membrane"/>
						<xsd:enumeration value="-"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TypeDigitalManometer">
		<xsd:restriction base="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Select the digital manometer to communicate with. "TH1" left placed digital manometer; "TH2" right placed digital manometer</xsd:documentation>
			</xsd:annotation>
			<xsd:enumeration value="TH1"/>
			<xsd:enumeration value="TH2"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypeMeasurementFrequency">
		<xsd:restriction base="xsd:integer">
			<xsd:annotation>
				<xsd:documentation>Select the measurement frequency of the digital manometer. Default 10, set 25 only for fingerprint use only. </xsd:documentation>
			</xsd:annotation>
			<xsd:enumeration value="10"/>
			<xsd:enumeration value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== evan-vivasoft/InspectorPC/38000405_Inspector_PC/SIOUX Source/Inspector.UI.Initialization/Data/XML/Kamstrup/InspectionProcedure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Liquid XML Data Binding Libraries (www.liquid-technologies.com) for Kamstrup b.v.-->
<InspectionProcedureFile xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="T:\SOURCE~1\INSPECTOR.PC\Data\XSD\InspectionProcedure.xsd">
	<InspectionProcedure>
		<Name>Visual Inspection Test</Name>
		<Version>1.1</Version>
		<InspectionSequence >
      <Scriptcommand_5x>
        <SequenceNumber>1</SequenceNumber>
        <ObjectName/>
        <MeasurePoint>00249</MeasurePoint>
        <FieldNo>15</FieldNo>
        <Scriptcommand>55</Scriptcommand>
        <Instruction>Geregelde waarde (Netdruk)</Instruction>
        <DigitalManometer>TH2</DigitalManometer>
        <MeasurementFrequency>10</MeasurementFrequency>
        <MeasurementPeriod>20</MeasurementPeriod>
        <ExtraMeasurementPeriod>10</ExtraMeasurementPeriod>
      </Scriptcommand_5x>
      </InspectionSequence >
	</InspectionProcedure>
</InspectionProcedureFile>

=== evan-vivasoft/InspectorPC/SIOUX Source/Inspector.UI.Initialization/Data/XML Kamstrup/InspectionProcedure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Liquid XML Data Binding Libraries (www.liquid-technologies.com) for Kamstrup b.v.-->
<InspectionProcedureFile xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="T:\SOURCE~1\INSPECTOR.PC\Data\XSD\InspectionProcedure.xsd">
	<InspectionProcedure>
		<Name>Visual Inspection Test</Name>
		<Version>1.1</Version>
		<InspectionSequence >
		<Scriptcommand_2>
			<SequenceNumber>1</SequenceNumber>
			<Section>Script command 41; Section; Sequence 19</Section>
			<SubSection>Script Command 41; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_41>
			<SequenceNumber>2</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00210</MeasurePoint>
			<FieldNo>11</FieldNo>
			<ShowNextListImmediately>false</ShowNextListImmediately>
			<List>
				<SequenceNumberList>1</SequenceNumberList>
				<ListType>0;OptionList</ListType>
				<SelectionRequired>true</SelectionRequired>
				<ListQuestion>Option List question</ListQuestion>
				<OneSelectionAllowed>true</OneSelectionAllowed>
				<CheckListResult>true</CheckListResult>
				<ListConditionCode>
					<ConditionCode>01/a</ConditionCode>
					<ConditionCodeDescription>01; Next list display</ConditionCodeDescription>
					<DisplayNextList>true</DisplayNextList>
				</ListConditionCode>
				<ListConditionCode>
					<ConditionCode>02/a</ConditionCode>
					<ConditionCodeDescription>02; No list display</ConditionCodeDescription>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
				<ListConditionCode>
					<ConditionCode>03/a</ConditionCode>
					<ConditionCodeDescription>03; No list display</ConditionCodeDescription>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
			</List>
			<List>
				<SequenceNumberList>2</SequenceNumberList>
				<ListType>1;CheckList</ListType>
				<SelectionRequired>true</SelectionRequired>
				<ListQuestion>Check list question</ListQuestion>
				<OneSelectionAllowed>false</OneSelectionAllowed>
				<CheckListResult>true</CheckListResult>
				<ListConditionCode>
					<ConditionCode>01/a</ConditionCode>
					<ConditionCodeDescription>01/b; Next list display</ConditionCodeDescription>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
				<ListConditionCode>
					<ConditionCode>02/b</ConditionCode>
					<ConditionCodeDescription>02/b; Next list display</ConditionCodeDescription>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
			</List>
			<List>
				<SequenceNumberList>3</SequenceNumberList>
				<ListType>0;OptionList</ListType>
				<SelectionRequired>true</SelectionRequired>
				<ListQuestion>Multiple selection; checklistresult = false</ListQuestion>
				<OneSelectionAllowed>false</OneSelectionAllowed>
				<CheckListResult>false</CheckListResult>
				<ListConditionCode>
					<ConditionCode>01/c</ConditionCode>
					<ConditionCodeDescription/>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
				<ListConditionCode>
					<ConditionCode>02/c</ConditionCode>
					<ConditionCodeDescription/>
					<DisplayNextList>false</DisplayNextList>
				</ListConditionCode>
			</List>
		</Scriptcommand_41>
		<Scriptcommand_2>
			<SequenceNumber>3</SequenceNumber>
			<Section>Script command 1; Section; Sequence 1</Section>
			<SubSection>Script Command 1; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_1>
			<SequenceNumber>4</SequenceNumber>
			<Text>Instruction to th user; SequenceNumber 2</Text>
		</Scriptcommand_1>
		<Scriptcommand_2>
			<SequenceNumber>5</SequenceNumber>
			<Section>Script command 3; Section; Sequence 3</Section>
			<SubSection>Script Command 3; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_3>
			<SequenceNumber>6</SequenceNumber>
			<Text>Pause; Duration 10 seconds; Sequence 4</Text>
			<Duration>10</Duration>
		</Scriptcommand_3>
		<Scriptcommand_2>
			<SequenceNumber>7</SequenceNumber>
			<Section>Script command 4; Section; Sequence 5</Section>
			<SubSection>Script Command 4; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_4>
			<SequenceNumber>8</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>33</FieldNo>
			<Question>Multi lines; Input required; Sequence 6</Question>
			<TypeQuestion>0; Input multi lines</TypeQuestion>
			<Required>true</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>9</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>1</FieldNo>
			<Question>Multi lines; No input required; Sequence 7</Question>
			<TypeQuestion>0; Input multi lines</TypeQuestion>
			<Required>false</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>10</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>2</FieldNo>
			<Question>Single line; Input required; Sequence 8</Question>
			<TypeQuestion>1; Input single line</TypeQuestion>
			<Required>true</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>11</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>3</FieldNo>
			<Question>Single line; No input required; Sequence 9</Question>
			<TypeQuestion>1; Input single line</TypeQuestion>
			<Required>false</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>12</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>4</FieldNo>
			<Question>2 Option; Input required; Sequence 10</Question>
			<TypeQuestion>2; 2 options</TypeQuestion>
			<TextOptions>Optie 1</TextOptions>
			<TextOptions>Optie 2</TextOptions>
			<Required>true</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>13</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>5</FieldNo>
			<Question>2 Option; no input required; Sequence 11</Question>
			<TypeQuestion>2; 2 options</TypeQuestion>
			<TextOptions>Optie 1</TextOptions>
			<TextOptions>Optie 2</TextOptions>
			<Required>false</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>14</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>6</FieldNo>
			<Question>3 Option; Input required; Sequence 12</Question>
			<TypeQuestion>3; 3 options</TypeQuestion>
			<TextOptions>Optie 1</TextOptions>
			<TextOptions>Optie 2</TextOptions>
			<TextOptions>Optie 3</TextOptions>
			<Required>true</Required>
		</Scriptcommand_4>
		<Scriptcommand_4>
			<SequenceNumber>15</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>7</FieldNo>
			<Question>3 Option; No input required; Sequence 13</Question>
			<TypeQuestion>3; 3 options</TypeQuestion>
			<TextOptions>Optie 1</TextOptions>
			<TextOptions>Optie 2</TextOptions>
			<TextOptions>Optie 3</TextOptions>
			<Required>false</Required>
		</Scriptcommand_4>
		<Scriptcommand_2>
			<SequenceNumber>16</SequenceNumber>
			<Section>Script command 43; Section; Sequence 14</Section>
			<SubSection>Script Command 43; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_43>
			<SequenceNumber>17</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>8</FieldNo>
			<Instruction>List required; 4 list items; Sequence 15</Instruction>
			<ListItem>ListItem 1</ListItem>
			<ListItem>ListItem 2</ListItem>
			<ListItem>ListItem 3</ListItem>
			<ListItem>ListItem 4</ListItem>
			<Required>true</Required>
		</Scriptcommand_43>
		<Scriptcommand_43>
			<SequenceNumber>18</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00205</MeasurePoint>
			<FieldNo>9</FieldNo>
			<Instruction>List not required; 20 list items; Sequence 16</Instruction>
			<ListItem>ListItem 1</ListItem>
			<ListItem>ListItem 2</ListItem>
			<ListItem>ListItem 3</ListItem>
			<ListItem>ListItem 4</ListItem>
			<ListItem>ListItem 5</ListItem>
			<ListItem>ListItem 6</ListItem>
			<ListItem>ListItem 7</ListItem>
			<ListItem>ListItem 8</ListItem>
			<ListItem>ListItem 9</ListItem>
			<ListItem>ListItem 10</ListItem>
			<ListItem>ListItem 11</ListItem>
			<ListItem>ListItem 12</ListItem>
			<ListItem>ListItem 13</ListItem>
			<ListItem>ListItem 14</ListItem>
			<ListItem>ListItem 15</ListItem>
			<ListItem>ListItem 16</ListItem>
			<ListItem>ListItem 17</ListItem>
			<ListItem>ListItem 18</ListItem>
			<ListItem>ListItem 19</ListItem>
			<ListItem>ListItem 20</ListItem>
			<Required>false</Required>
		</Scriptcommand_43>
		<Scriptcommand_2>
			<SequenceNumber>19</SequenceNumber>
			<Section>Script command 42; Section; Sequence 17</Section>
			<SubSection>Script Command 42; Sub Section </SubSection>
		</Scriptcommand_2>
		<Scriptcommand_42>
			<SequenceNumber>20</SequenceNumber>
			<ObjectName/>
			<MeasurePoint>00134</MeasurePoint>
			<FieldNo>10</FieldNo>
		</Scriptcommand_42>
		</InspectionSequence >
	</InspectionProcedure>
</InspectionProcedureFile>
