=== evan-vivasoft/InspectorPC/38000405_Inspector_PC/SIOUX Source/Inspector.UI.Initialization/Data/XSD/InspectionStatus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 sp1 (http://www.altova.com) by Michel De Clercq (Kamstrup b.v.) -->
<!-- Made by Michel de Clercq (Kamstrup b.v.) Version 2.0 Date 19-12-2006 -->
<!-- The inspection status of the gas control line and the pressure regulator station are save in this file. If no status is present, the inspection did not started-->
<!--Version 2.1 Add GCLCode to node InspectionStatus Date 23-10-2008-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Status">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="InspectionStatus" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PRSIdentification" type="xs:string"/>
							<xs:element name="PRSName" type="xs:string"/>
							<xs:element name="PRSCode" type="xs:string"/>
							<xs:element name="GCLIdentification" type="xs:string" minOccurs="0"/>
							<xs:element name="GasControlLineName" type="xs:string" minOccurs="0"/>
							<xs:element name="GCLCode" type="xs:string" minOccurs="0"/>
							<xs:element name="StatusID" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== evan-vivasoft/InspectorPC/SIOUX Source/Inspector.UI.Initialization/KAM.COMMUNICATOR.UI.Test/Test Files/InspectionStatus.xml
<?xml version="1.0" encoding="utf-8"?>
<Status xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="T:\SOURCE~1\INSPECTOR.PC\SOURCE~1\KAM.COMMUNICATOR.UI.Test\bin\Debug\TESTFI~1\InspectionStatus.xsd">
	<InspectionStatus>
		<PRSIdentification>697</PRSIdentification>
		<PRSName>G00002</PRSName>
		<PRSCode>G00002</PRSCode>
		<StatusID>2</StatusID>
	</InspectionStatus>
	<InspectionStatus>
		<PRSIdentification>5 007 230.1</PRSIdentification>
		<PRSName>G00002</PRSName>
		<PRSCode>G00002</PRSCode>
		<GCLIdentification>23.05.2012 5 007 230.1.1</GCLIdentification>
		<GasControlLineName>5 007 230.1.1 OS LS</GasControlLineName>
		<GCLCode/>
		<StatusID>2</StatusID>
	</InspectionStatus>
	<InspectionStatus>
		<PRSIdentification>5 007 230.1</PRSIdentification>
		<PRSName>G00004</PRSName>
		<PRSCode>G00004</PRSCode>
		<StatusID>3</StatusID>
	</InspectionStatus>
</Status>
